### PR TITLE
Fix aiohttp usage, support simple types as return values & add overridable data_encoder function

### PR DESCRIPTION
**Pull request by kizill**

### CODE REVIEW

**Comment by ponytailer** [comment]
Add tests for the simple type， please

**Comment by kizill** [comment]
Hi! I've dropped all the monkeypatching and implemented real server startup so testing real libraries with real requests.

**Comment by kizill** [comment]
Hi! Can you review this PR?

**Comment by ponytailer** [comment]
> Hi! Can you review this PR?

lgtm

**Pull request merged**
